ALTER TABLE deliveries
    ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(200),
    ADD COLUMN IF NOT EXISTS recipient_phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS picked_up_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS location_updated_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS courier_latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS courier_longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS cargo_company VARCHAR(100),
    ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(100);